### ISSUE TITLE
Not working properly.

### ISSUE THREAD

**Issue by shankhadevpadam** [vanilophp/framework#128]
Installed the application after following these two steps and run the app and get the error below.

https://vanilo.io/docs/3.x/installation

https://vanilo.io/docs/3.x/admin-installation

```php
Route [vanilo.admin.product.index] not defined.
```

**Comment by fulopattila122** [comment]
Did you add the Admin module to `config/concord.php`?

**Comment by shankhadevpadam** [comment]
```php
return [
    'modules' => [
        Vanilo\Foundation\Providers\ModuleServiceProvider::class,
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'Shop Admin', // Your app's name to display on admin
                'url'  => '/admin/dashboard', // Base/Home URL after login (eg. dashboard)
                'routes' => [
                    'prefix' => 'admin',
                ],
            ],
        ],
        Vanilo\Admin\Providers\ModuleServiceProvider::class => [
            'routes' => [
                'prefix' => 'admin',
            ],  
        ],
    ],
    'register_route_models' => true
];
```

**Comment by fulopattila122** [comment]
Use this instead:

```php
return [
    'modules' => [
        Vanilo\Foundation\Providers\ModuleServiceProvider::class,
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'Shop Admin', // Your app's name to display on admin
                'url'  => '/admin/dashboard', // Base/Home URL after login (eg. dashboard)
            ],
        ],
        Vanilo\Admin\Providers\ModuleServiceProvider::class,
    ],
    'register_route_models' => true
];
```

The reason is that the `routes => [prefix => 'admin']` entries in the config are both redundant (the prefix is admin anyway), and erroneous since it doesn't include the route file definitions of [appshell](https://github.com/artkonekt/appshell/blob/3.x/src/resources/config/box.php#L40) and [admin](https://github.com/vanilophp/admin/blob/master/src/resources/config/box.php#L10).

When using custom route config, those values from the default module config need to be present as well.
This is due to how Laravel's [Config::set()](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Config/Repository.php#L87) method works, it overwrites nested config arrays.

**Comment by peterson-umoke** [comment]
People keep making this same mistake because of the documentation [here](https://vanilo.io/docs/3.x/admin-basics). Please where can we make PR for this.

**Comment by fulopattila122** [comment]
https://github.com/vanilophp/docs
