### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by fnocetti** [vanilophp/framework#17]
Hello @fulopattila122 ,
I'm really interested in your project and wanted to know if you are still working on it or I should consider it abandoned.

Thanks!

**Comment by fulopattila122** [comment]
Hi, yes it's still maintained, actually new release comes in 1-2 days, hopefully today.

Please note that Vanilo is not (yet) a monorepo and the work is done within various [module repositories](https://github.com/vanilophp).

The roadmap is also about to change so that 1.0 will be still released this year.

So yes, new release in 1-2 days! :)

**Comment by de-raaf-media** [comment]
Hello  @fulopattila122. I'm also very interested and looking forward to a stable release. Can you give a status update?

**Comment by fulopattila122** [comment]
Yes it is. We slid off the release plan but v0.5 is on its way. It'll come within the next 10 days. After that v1.0 is the next.

I'll update the roadmap tomorrow.

**Comment by de-raaf-media** [comment]
Cool! 👍
