### ISSUE TITLE
Exception throws while editing pictures for product

### ISSUE THREAD

**Issue by learn2develop** [vanilophp/framework#28]
https://github.com/vanilophp/framework/blob/master/src/resources/views/product/_edit_images.blade.php#L41

The form in my code was missing the ``` 'for'=>'product' ``` so I have changed it to the code below

```php
{!! Form::open(['route' => ['vanilo.media.store', 'for'=>'product' ], 'enctype'=>'multipart/form-data', 'class' => 'card']) !!}
```
if fixed, please ignore.

**Comment by fulopattila122** [comment]
Thank you for the report.

The "missing" field is actually 3 lines below:
https://github.com/vanilophp/framework/blob/master/src/resources/views/product/_edit_images.blade.php#L44

And it seems to be working on all instances/tests I know.
But since you've been reporting some issues related to this, there's definitely some problem there, so I'd prefer to get more Information to find the problem.

What happens if you remove `'for' => 'prodcut'` from the form definition while having the field below within the form?

```php
{{ Form::hidden('for', 'product') }}
```

**Comment by learn2develop** [comment]
Oops, yes it is there, sorry. However, if I remove it from the form definition an exception is thrown
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function addMultipleMediaFromRequest() on null
```
