### ISSUE TITLE
ideas of shipment handling

### ISSUE THREAD

**Issue by txlife** [vanilophp/framework#33]
Hi there,

Would you be able to share some your basic concepts of shipment handling. We currently are starting up a new project and would like to use Vanilo as the framework. However, we don't think we will have the time to wait until the shipment feature's release. To avoid trouble for further upgrading, it might be good if we can implement similar concepts regarding the shipment handling. It would be greater if you could provide some ideas for order processing as well.

For the payment feature, would there be possibilities for us to add on customized payment channel?

Thanks and regards

**Comment by fulopattila122** [comment]
Hey, thanks for contacting, cool to hear you want to build on top of Vanilo.

Since we're young players I prefer to prioritize every real shop implementation so I'm open to rearrange some priorities. Can you please contact me privately either on twitter or gmail (username is the same as here)?

Thank you

**Comment by ghermans** [comment]
Hi, what is the status of this feature?
