### ISSUE TITLE
Foreign key constraint is incorrectly formed on fresh installation 

### ISSUE THREAD

**Issue by Sohib** [vanilophp/framework#42]
i'm following the installation instruction but i have encountered this issue twice, when running 
`php artisan migrate`

i get this error message 

```
Migrating: 2016_12_18_121118_create_profiles_table

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Can't create table `vanilo`.`#sql-9a5_a6` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `profiles` add constraint `profiles_user_id_foreign` foreign key (`user_id`) references `users` (`id`))

  at vaniloapp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `vanilo`.`#sql-9a5_a6` (errno: 150 "Foreign key constraint is incorrectly formed")")
      vaniloapp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      vaniloapp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

```

my database is  `Server version: 10.2.18-MariaDB - Homebrew`

**Comment by Sohib** [comment]
my laravel version is Laravel Framework 5.8.8

i think i know what caused this issue laravel uses `$table->bigIncrements('id');` for users table while vanilo uses `$table->integer('user_id')->unsigned();` normal integer in should be `bigInteger`

**Comment by yusufkandemir** [comment]
This issue is about **[artkonekt/user](https://github.com/artkonekt/user)** package and changes in Laravel 5.8, which is caused by [this line](https://github.com/artkonekt/user/blob/772665b3d08142402838810e2326fff41029dec9/src/resources/database/migrations/2016_12_18_121118_create_profiles_table.php#L17).

```php
$table->integer('user_id')->unsigned();
```

In Laravel 5.8, they [changed](https://github.com/laravel/laravel/commit/426df7a0e4d489439002cf99c37246aeebdc5327) type of `id` columns from `increments` to `bigIncrements` in `create_users_table` migration and migration stubs. They state this change in [docs](https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0) as:

> ### **Migrations & `bigIncrements`**
> #### Likelihood Of Impact: None

It looks like it actually has impact not because they changed migration stubs but `create_users_table` migration too.


If the line in **[artkonekt/user](https://github.com/artkonekt/user)** package is changed as follows:
```diff
- $table->integer('user_id')->unsigned();
+ $table->bigInteger('user_id')->unsigned();
```
the problem with Laravel 5.8 will be solved. But then unfortunately this solution will conflict with older Laravel versions.

**Comment by hamzaPlanet** [comment]
In laravel 5.8
            $table->bigIncrements('id');
            $table->bigInteger('user_id')->unsigned();

**Comment by fulopattila122** [comment]
Version 1.1.0 of the [User Module](https://konekt.dev/user) has been released - that fixes this issue.
