### ISSUE TITLE
Vanilo 2.x is incompatible with PHP 7.3?

### ISSUE THREAD

**Issue by r8928** [vanilophp/framework#94]
[Installation requirements](https://vanilo.io/docs/2.x/installation) mentions PHP 7.3 or higher is required, however the library's [composer.json](https://github.com/vanilophp/framework/blob/2.0.0/composer.json) has minimum requirement of PHP 7.4 resulting in this while installing:

`
[InvalidArgumentException]
Package vanilo/framework at version 2 has a PHP requirement incompatible with your PHP version (7.3.12)
`

**Comment by fulopattila122** [comment]
All the standalone components are PHP 7.3 compatible, but the Framework requires PHP 7.4+

The reason behind the higher requirements is that it uses the [Spatie Media Library](https://spatie.be/docs/laravel-medialibrary/v8/requirements) that requires 7.4+ (and Laravel v6.18+)

Since PHP 7.3 is EOL, the standalone components will also bump the minimum PHP requirements to PHP 7.4+ soon.
